blank_issues_enabled: true
contact_links:
  - name: Zetacoin Core Security Policy
    url: https://github.com/tuaris/zetacoin/blob/master/SECURITY.md
    about: View security policy
  - name: Zetacoin Core
    url: https://www.getzetacoin.com
    about: Zetacoin Core homepage
