#!/usr/bin/env bash
#
#  zetacoind The zetacoin core server.
#
#
# chkconfig: 345 80 20
# description: zetacoind
# processname: zetacoind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/zetacoind, see below
if [ -f /etc/sysconfig/zetacoind ]; then
        . /etc/sysconfig/zetacoind
fi

RETVAL=0

prog=zetacoind
# you can override the lockfile via ZETACOIND_LOCKFILE in /etc/sysconfig/zetacoind
lockfile=${ZETACOIND_LOCKFILE-/var/lock/subsys/zetacoind}

# zetacoind defaults to /usr/bin/zetacoind, override with ZETACOIND_BIN
zetacoind=${ZETACOIND_BIN-/usr/bin/zetacoind}

# zetacoind opts default to -disablewallet, override with ZETACOIND_OPTS
zetacoind_opts=${ZETACOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $zetacoind $zetacoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
