description "Zetacoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env ZETACOIND_BIN="/usr/bin/zetacoind"
env ZETACOIND_USER="zetacoin"
env ZETACOIND_GROUP="zetacoin"
env ZETACOIND_PIDDIR="/var/run/zetacoind"
# upstart can't handle variables constructed with other variables
env ZETACOIND_PIDFILE="/var/run/zetacoind/zetacoind.pid"
env ZETACOIND_CONFIGFILE="/etc/zetacoin/zetacoin.conf"
env ZETACOIND_DATADIR="/var/lib/zetacoind"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # zetacoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$ZETACOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run zetacoind."
        echo "The setting must appear in $ZETACOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Zetacoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$ZETACOIND_PIDDIR"
    chmod 0755 "$ZETACOIND_PIDDIR"
    chown $ZETACOIND_USER:$ZETACOIND_GROUP "$ZETACOIND_PIDDIR"
    chown $ZETACOIND_USER:$ZETACOIND_GROUP "$ZETACOIND_CONFIGFILE"
    chmod 0660 "$ZETACOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$ZETACOIND_PIDFILE" \
    --chuid $ZETACOIND_USER:$ZETACOIND_GROUP \
    --exec "$ZETACOIND_BIN" \
    -- \
    -pid="$ZETACOIND_PIDFILE" \
    -conf="$ZETACOIND_CONFIGFILE" \
    -datadir="$ZETACOIND_DATADIR" \
    -disablewallet \
    -daemon

